### ISSUE TITLE
Came Antifurto

### ISSUE THREAD

**Issue by Ringo982** [Den901/ha_came#1]
Ciao, sai dirmi se posso utilizzare la tua soluzione per controllare un antifurto PCX2-32 che al momento sto controllando tramite l'app Came Domotic 3.0? Grazie

**Comment by Den901** [comment]
Al momento la libreria non controlla ancora l’antifurto sfortunatamente, si può sviluppare però

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Ringo982 ***@***.***>
Inviato: Friday, January 6, 2023 12:05:02 PM
A: Den901/ha_came ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Den901/ha_came] Came Antifurto (Issue #1)


Ciao, sai dirmi se posso utilizzare la tua soluzione per controllare un antifurto PCX2-32 che al momento sto controllando tramite l'app Came Domotic 3.0? Grazie

**Comment by odoricof** [comment]
Ciao, se può servire io ho la centrale installata sotto ETI/DOMO.

**Comment by Den901** [comment]
Ciao, attualmente sto lavorando per integrare la parte di sicurezza
