### ISSUE TITLE
Error updating from HACS

### ISSUE THREAD

**Issue by odoricof** [Den901/ha_came#3]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.hacs
Source: custom_components/hacs/websocket/repository.py:48
Integration: HACS (documentation, issues)
First occurred: 10:26:11 (1 occurrences)
Last logged: 10:26:11

<Integration Den901/ha_came> No manifest.json file found 'custom_components/custom_components_test/manifest.json'

**Comment by Den901** [comment]
Ciao, l’integrazione non è ancora su hacs… va installata a mano

Il giorno gio 2 nov 2023 alle 10:38 Flavio Odorico ***@***.***>
ha scritto:
