### ISSUE TITLE
shutters

### ISSUE THREAD

**Issue by Tanc91** [Den901/ha_came#6]
Is there a way to get shutters into the integrations? thanks in advance

**Comment by Den901** [comment]
Hi! Shutter are working 😊

 

 

 

 

Cordialmente 

Mauro Danny

IT Manager – Company Director

ACTA Soc. Coop. 

Via Roma 24 33051 – Aquileia UD

Tel. 0431-476626 Tasto 2

Email: ***@***.***



 


	
		
 

 


Questo messaggio di posta elettronica contiene informazioni di carattere confidenziale rivolte esclusivamente al destinatario sopra indicato.

E' vietato l'uso, la diffusione, distribuzione o riproduzione da parte di ogni altra persona. Nel caso aveste ricevuto questo messaggio di posta elettronica per errore, siete pregati di segnalarlo immediatamente al mittente e distruggere quanto ricevuto (compresi i file allegati) senza farne copia.

Qualsivoglia utilizzo non autorizzato del contenuto di questo messaggio costituisce violazione dell'obbligo di non prendere cognizione della corrispondenza tra altri soggetti, salvo più grave illecito, ed espone ilresponsabile alle relative conseguenze.

 

In ogni momento l'interessato del messaggio ha diritto di opporsi al trattamento dei propri dati per invio di comunicazioni commerciali, di materiale pubblicitario o di vendita diretta, inviando una e-mail al sottostante indirizzo. L'interessato può inoltre esercitare tutti i suoi diritti di accesso ai propri dati personali come previsto dall'art. 7 del D.Lgs. n. 196/2003 tra i quali rettifica, aggiornamento e cancellazione inviando un messaggio al seguente indirizzo:  ***@***.***>  ***@***.***

 

Tutela dell'idea e progettazione 

(nel caso questa mail contenga progetti, elaborati o opere di ACTA soc. Coop.)

A tutela delle realizzazioni intellettuali per l'ideazione e progettazione di questo, come di eventuali successivi lavori, resta inteso che le proposte presentate sono vincolate dalla legge sui diritti d'autore, per cui è fatto divieto di avvalersene, in toto o in parte, senza il preventivo accordo per l'assegnazione dell'incarico di consulenza globale per l'utilizzo del progetto presentato.

 

 

 

Da: Tanc91 ***@***.***> 
Inviato: martedì 19 marzo 2024 23:33
A: Den901/ha_came ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Den901/ha_came] shuuters (Issue #6)

 

Is there a way to get shutters into the integrations? thanks in advance

**Comment by Tanc91** [comment]
Ciao Danny, allora probabilmente ho sbagliato qualcosa nell'aggiunta
dell'integrazione perché non mi appaiono tra le entità.
Grazie mille per la risposta e la disponibilità

Buona giornata



Il Mer 20 Mar 2024, 08:11 Danny Mauro ***@***.***> ha scritto:

**Comment by Den901** [comment]
Dipende tutto da come sono configurati sul came d-sw…. Testa la libreria
con il terminale e guarda se rileva la voce openings

Il giorno mer 20 mar 2024 alle 08:39 Tanc91 ***@***.***> ha
scritto:

**Comment by mohamed-mehany** [comment]
Hi @Den901 
I'm also having a similar issue.
I think the cover class only exists here: https://github.com/Den901/ha_came/blob/main/custom_components_test/came/cover.py but not in the main came directory: https://github.com/Den901/ha_came/tree/main/came
